services:
  paddibot:
    container_name: paddibot
    image: ghcr.io/japabu/paddibot:latest
    environment:
      CLIENT_ID: 1170359617134534736
      TOKEN: MTE3MDM1OTYxNzEzNDUzNDczNg.GNPjBt.cenwFm9oUatMQu44vAp2VQsOtz7Mv_9ThQc2_0
  blunderbot:
    container_name: blunderbot
    image: ghcr.io/japabu/blunderbot:latest
    environment:
      CLIENT_ID: 1172565845839462481
      TOKEN: MTE3MjU2NTg0NTgzOTQ2MjQ4MQ.G2XFpz.-LvdRF6AvxYlRobmxRB04-boChbn6MlBgdrryw
      STOCKFISH_SERVER_URL: http://stockfish-server:3000
  stockfish-server:
    container_name: stockfish-server
    image: ghcr.io/japabu/stockfish-server:latest
    privileged: true
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: always
    command:
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=japa.busse@gmail.com
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
  henk:
    image: ghcr.io/japabu/henk:latest
    container_name: henk
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.henk.rule=Host(`henk.pi.japabu.ch`)"
      - "traefik.http.routers.henk.entrypoints=websecure"
      - "traefik.http.routers.henk.tls.certresolver=letsencrypt"
      - "traefik.http.services.henk.loadbalancer.server.port=80"
  memescraper:
    image: ghcr.io/japabu/memescraper:latest
    container_name: memesraper
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.memesraper.rule=Host(`memesraper.pi.japabu.ch`)"
      - "traefik.http.routers.memesraper.entrypoints=websecure"
      - "traefik.http.routers.memesraper.tls.certresolver=letsencrypt"
      - "traefik.http.services.memesraper.loadbalancer.server.port=80"
  flappy:
    image: ghcr.io/japabu/flappy:latest
    container_name: flappy
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flappy.rule=Host(`flappy.pi.japabu.ch`)"
      - "traefik.http.routers.flappy.entrypoints=websecure"
      - "traefik.http.routers.flappy.tls.certresolver=letsencrypt"
      - "traefik.http.services.flappy.loadbalancer.server.port=80"
      